import * as vscode from 'vscode';
import * as path from 'node:path';
import { stat, mkdtemp, mkdir, writeFile, rm, cp, readFile, realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';
import { Exercise } from '../src/core';
import { Previews } from '../src/preview';
import { Runner } from '../src/runner';
import { errorStatus } from '../src/errors';
import { exerciseFromTemplate, sheetFromTemplate, contestFromTemplate, creationPath } from '../src/typst';
import { forward } from '../src/tinymist';
import { Browser } from '../src/browser';
import { searchItem, searchPicker } from '../src/search';
import { isFolder } from '../src/tree';
import { Sheets, memberItem } from '../src/sheets';
import { relocated, moveSource, directories } from '../src/files';
import { sheetList, sourceMetadata } from '../src/sheet-model';
import { Drag } from '../src/drag';
import { documentTemplates } from '../src/authoring';
import { identify } from '../src/documents';

async function until(condition: () => boolean | Promise<boolean>, message: string): Promise<void> {
  const deadline = Date.now() + 20_000;
  while (Date.now() < deadline) { if (await condition()) return; await new Promise(resolve => setTimeout(resolve, 100)); }
  throw new Error(message);
}

export async function run(): Promise<void> {
  const extension = vscode.extensions.getExtension('qfortier.vscode-exercices-mpi');
  assert.ok(extension, 'Extension chargée');
  const api = await extension.activate();
  assert.ok(api.getEntries().length > 0, 'Banque détectée avec lib/exercice.typ');
  const manifest = extension.packageJSON.contributes;
  const commands = await vscode.commands.getCommands(true);
  assert.deepEqual(manifest.views.exercicesMpi.map((view: { id: string }) => view.id), ['exercicesMpi.current', 'exercicesMpi.library', 'exercicesMpi.sheets']);
  assert.equal(manifest.views.exercicesMpi.at(-1).name, 'Feuilles');
  for (const section of ['current', 'library', 'sheets']) {
    await vscode.commands.executeCommand(`exercicesMpi.${section}.focus`);
    assert.ok((await vscode.commands.getCommands(true)).includes(`workbench.actions.treeView.exercicesMpi.${section}.collapseAll`));
    await vscode.commands.executeCommand(`exercicesMpi.collapse${section}`);
  }
  for (const binding of manifest.keybindings) assert.ok(commands.includes(binding.command), binding.command);
  for (const item of manifest.menus['view/title']) {
    if (/toggle|collapse/.test(item.command)) assert.ok(!item.group.startsWith('navigation'));
    if (/reset/.test(item.command)) assert.ok(item.when.includes('searchActive'));
  }
  for (const uri of await vscode.workspace.findFiles('feuilles/**/*.typ')) {
    const doc = await vscode.workspace.openTextDocument(uri);
    sheetList(doc.getText(), path.relative(process.env.EXERCICES_MPI_BANK!, uri.fsPath));
  }
  const sheetFiles = await vscode.workspace.findFiles('feuilles/**/*.typ');
  const nestedSheet = sheetFiles.find(uri => path.relative(process.env.EXERCICES_MPI_BANK!, uri.fsPath).split(path.sep).length > 2) ?? sheetFiles[0];
  assert.ok(nestedSheet, 'Une feuille existante pour tester reveal');
  const revealed = await api.revealSheet(path.relative(process.env.EXERCICES_MPI_BANK!, nestedSheet.fsPath));
  assert.equal(revealed.source, path.relative(process.env.EXERCICES_MPI_BANK!, nestedSheet.fsPath), 'Sélection réelle de la feuille avec TreeView.reveal');
  const results: Exercise[] = api.search('monoides', { concours: 'ENS' });
  assert.ok(results.some(ex => ex.fichier.endsWith('/automates-monoides.typ')));
  const bank = process.env.EXERCICES_MPI_BANK!;
  // No generated bank PDF is opened or inspected.
  const temporary = await realpath(await mkdtemp(path.join(tmpdir(), 'exercices-mpi-preview-')));
  const previewBank = { root: temporary, name: 'Test isolé', scope: vscode.Uri.file(temporary) };
  const previews = new Previews({ extensionUri: extension.extensionUri } as vscode.ExtensionContext, async () => undefined);
  const runner = new Runner();
  const sockets: WebSocket[] = [];
  try {
    for (const file of ['lib', 'templates', 'scripts', 'Makefile', 'flake.nix', 'flake.lock']) await cp(path.join(bank, file), path.join(temporary, file), { recursive: true });
    for (const directory of ['exercices/graphes', 'feuilles', 'devoirs/2026-2027', 'concours']) await mkdir(path.join(temporary, directory), { recursive: true });
    const customTemplate = (await readFile(path.join(temporary, 'templates/devoir.typ'), 'utf8')).replace('type: "devoir"', 'type: "colle"');
    await writeFile(path.join(temporary, 'templates/colle.typ'), customTemplate);
    assert.deepEqual((await documentTemplates(previewBank)).map(template => template.type).sort(), ['colle', 'concours', 'devoir', 'td']);
    const relative = 'exercices/graphes/test-creation.typ';
    const generated = exerciseFromTemplate(await readFile(path.join(bank, 'templates/exercice.typ'), 'utf8'), {
      title: 'Test création', chapters: ['graphes'], algorithms: [], structures: [], languages: [], levels: ['MPI'], difficulty: 2, minutes: 20
    }).replace('Énoncé à compléter.', '#heading(level: 2)[Repère du test]\n      Un texte unique avec une formule $x^2 + y^2 = z^2$.').replace('solution: none', 'solution: [#heading(level: 2)[Repère du corrigé] Une correction.]');
    const file = path.join(temporary, relative);
    await writeFile(file, generated);
    const editor = await vscode.window.showTextDocument(vscode.Uri.file(file), { viewColumn: vscode.ViewColumn.One });
    const before = Date.now();
    const preview = await previews.open(previewBank, relative, 'enonce');
    assert.equal(preview.panel.title, 'test-creation.pdf');
    assert.equal((preview.panel.iconPath as vscode.Uri).path, vscode.Uri.joinPath(extension.extensionUri, 'media', 'pdf.svg').path);
    console.log('Démarrage aperçu (ms)', Date.now() - before);
    let frames = 0;
    const listener = preview.panel.webview.onDidReceiveMessage(message => { if (message.type === 'frameReady') frames++; });
    await until(() => frames > 0, "L'iframe Tinymist ne se charge pas");
    const enonce = preview.sessions.get('enonce')!;
    const nativeHtml = await (await fetch(enonce.url)).text();
    assert.ok(nativeHtml.includes('html.exercices-jumps .typst-text:hover'));
    let documentOutline: any;
    enonce.connection.onNotification('tinymist/documentOutline', outline => { documentOutline = outline; });
    const socket = new WebSocket(`ws://127.0.0.1:${enonce.port}`);
    sockets.push(socket);
    const messages: Buffer[] = [];
    socket.binaryType = 'arraybuffer';
    socket.addEventListener('message', event => { const data = typeof event.data === 'string' ? Buffer.from(event.data) : Buffer.from(event.data as ArrayBuffer); messages.push(data); });
    await until(() => socket.readyState === WebSocket.OPEN, 'Connexion au rendu Tinymist');
    socket.send('current');
    await until(() => messages.some(data => /^(new|diff-v1),/.test(data.toString())), 'Rendu vectoriel initial');
    const dark = [vscode.ColorThemeKind.Dark, vscode.ColorThemeKind.HighContrast].includes(vscode.window.activeColorTheme.kind);
    assert.ok(messages.some(data => data.toString().includes(`"rest":"${dark ? 'always' : 'never'}"`)), 'Thème de rendu correct');
    const count = messages.length;
    const edit = new vscode.WorkspaceEdit();
    const line = generated.split('\n').findIndex(text => text.includes('Un texte unique'));
    edit.insert(editor.document.uri, new vscode.Position(line, 7), 'MODIFICATION ');
    await vscode.workspace.applyEdit(edit);
    await until(() => messages.slice(count).some(data => /^(new|diff-v1),/.test(data.toString())), 'Mise à jour sans enregistrer');
    const startJump = messages.length;
    editor.selection = new vscode.Selection(line, 20, line, 20);
    await forward(enonce, editor);
    await until(() => messages.slice(startJump).some(data => data.toString().startsWith('jump,')), 'Saut source vers aperçu');
    await until(() => !!documentOutline?.items?.length, 'Plan exact produit par Tinymist');
    assert.ok(!JSON.stringify(documentOutline).includes('Repère du corrigé'), 'Énoncé sans solution');
    const headingLine = generated.split('\n').findIndex(text => text.includes('Repère du test'));
    editor.selection = new vscode.Selection(0, 0, 0, 0);
    await enonce.connection.sendRequest('workspace/executeCommand', { command: 'tinymist.scrollPreview', arguments: [enonce.id, { event: 'sourceScrollBySpan', span: documentOutline.items[0].span }] });
    await until(() => vscode.window.activeTextEditor?.document.uri.fsPath === file && vscode.window.activeTextEditor.selection.start.line === headingLine, 'Saut inverse vers la position source exacte');
    await preview.toggleJumps();
    editor.selection = new vscode.Selection(0, 0, 0, 0);
    const noJump = messages.length;
    await previews.sync(editor);
    await enonce.connection.sendRequest('workspace/executeCommand', { command: 'tinymist.scrollPreview', arguments: [enonce.id, { event: 'sourceScrollBySpan', span: documentOutline.items[0].span }] });
    await new Promise(resolve => setTimeout(resolve, 250));
    assert.equal(editor.selection.start.line, 0, 'Saut inverse désactivé');
    assert.ok(!messages.slice(noJump).some(data => data.toString().startsWith('jump,')), 'Saut direct désactivé');
    await preview.toggleJumps();
    await preview.select('corrige');
    assert.equal(preview.panel.title, 'test-creation-cor.pdf');
    let correctedOutline: any;
    preview.sessions.get('corrige')!.connection.onNotification('tinymist/documentOutline', outline => { correctedOutline = outline; });
    const secondEdit = new vscode.WorkspaceEdit();
    secondEdit.insert(editor.document.uri, new vscode.Position(line, 7), 'SUITE ');
    await vscode.workspace.applyEdit(secondEdit);
    await until(() => JSON.stringify(correctedOutline)?.includes('Repère du corrigé') ?? false, 'Le corrigé affiche réellement les solutions');
    assert.equal(preview.sessions.size, 2);
    const switchStart = Date.now();
    await preview.select('enonce');
    assert.equal(preview.sessions.get('enonce'), enonce, 'La bascule réutilise le compilateur');
    console.log('Bascule chaude (ms)', Date.now() - switchStart);
    const compilationMessages: string[] = [];
    const originalPost = preview.panel.webview.postMessage.bind(preview.panel.webview);
    preview.panel.webview.postMessage = message => { if (message.type === 'compileError') compilationMessages.push(message.message); return originalPost(message); };
    const validText = editor.document.getText();
    const invalid = new vscode.WorkspaceEdit();
    invalid.insert(editor.document.uri, editor.document.positionAt(validText.length), '\n#let broken = (');
    await vscode.workspace.applyEdit(invalid);
    await new Promise(resolve => setTimeout(resolve, 300));
    assert.ok(!compilationMessages.some(Boolean), 'Pas de bandeau pendant la saisie');
    await until(() => compilationMessages.some(Boolean), 'Erreur de compilation transmise au bandeau PDF');
    const repair = new vscode.WorkspaceEdit();
    repair.delete(editor.document.uri, new vscode.Range(editor.document.positionAt(validText.length), editor.document.positionAt(editor.document.getText().length)));
    await vscode.workspace.applyEdit(repair);
    await until(() => compilationMessages.at(-1) === '', 'Bandeau effacé après correction');
    preview.panel.webview.postMessage = originalPost;
    await assert.rejects(stat(path.join(temporary, 'build')), 'Aucun make/PDF pour afficher ou basculer');
    await editor.document.save();
    await runner.run(previewBank, ['c', relative]);
    let journalOpened = 0;
    const originalShow = runner.output.show.bind(runner.output);
    runner.output.show = () => { journalOpened++; };
    await assert.rejects(runner.run(previewBank, ['missing-test-target']), /compilation a échoué/);
    assert.equal(journalOpened, 0, "L'erreur n'ouvre pas le journal automatiquement");
    await vscode.commands.executeCommand('exercicesMpi.showErrorDetails');
    assert.equal(journalOpened, 0, "Le clic ouvre Problems, jamais le journal");
    errorStatus.clear(`build:${previewBank.root}:missing-test-target`);
    runner.output.show = originalShow;
    for (const variant of ['enonce', 'corrige']) assert.ok((await stat(path.join(temporary, 'build/exercices/graphes/test-creation', `${variant}.pdf`))).size > 1000);
    const entries = results.slice(0, 1).map(ex => ({ bank: previewBank, ex }));
    const state = { get: (_key: string, fallback: unknown) => fallback, update: async () => undefined } as unknown as vscode.Memento;
    const browser = new Browser('exercices', state);
    browser.entries = entries.map(item => ({ ...item, source: item.ex.fichier }));
    const choice = searchItem(browser.entries[0]);
    assert.ok(choice.description?.includes(browser.entries[0].source));
    assert.ok(choice.detail?.includes('ENS'));
    assert.equal(browser.search('monoides').length, 1);
    const chooseFile = searchPicker(browser);
    await vscode.commands.executeCommand('workbench.action.acceptSelectedQuickOpenItem');
    assert.equal(await chooseFile, browser.entries[0]);
    const cancelSearch = searchPicker(browser);
    await vscode.commands.executeCommand('workbench.action.closeQuickOpen');
    assert.equal(await cancelSearch, undefined);
    assert.equal(browser.getTreeItem(browser.entries[0]).checkboxState, undefined);
    assert.equal(browser.getTreeItem(browser.entries[0]).resourceUri?.fsPath, path.join(previewBank.root, browser.entries[0].source));
    assert.equal(browser.search('absent').length, 0);
    assert.equal(browser.visible.length, 1, 'La recherche ne filtre pas la vue');
    assert.ok(isFolder(browser.getChildren()[0]));
    assert.equal(browser.searching, false);
    browser.filters = { concours: 'ENS' }; assert.equal(browser.searching, true); browser.filters = {};
    const parent = browser.getParent(browser.entries[0]);
    assert.ok(parent && isFolder(parent));
    assert.equal(browser.getTreeItem(parent).resourceUri?.fsPath, parent.folder);
    assert.equal(browser.getParent(browser.entries[0]), parent, 'Identité du dossier stable');
    assert.ok(browser.getParent(parent), 'Dossier physique exercices conservé');
    browser.toggle(); assert.ok(!isFolder(browser.getChildren()[0]));
    assert.equal(browser.getParent(browser.entries[0]), undefined);
    browser.dispose();
    const sheetBrowser = new Browser('documents', state);
    sheetBrowser.entries = [{ bank: previewBank, source: 'feuilles/td.typ', documentType: 'td', metadata: [sourceMetadata('titre: "Série spéciale"', 'feuilles/td.typ'), entries[0].ex] }];
    sheetBrowser.filters = { concours: 'ENS' };
    assert.equal(sheetBrowser.search('speciale monoides').length, 1, 'Titre de feuille combiné aux métadonnées de ses exercices');
    sheetBrowser.filters = { concours: 'X' }; assert.equal(sheetBrowser.visible.length, 0);
    sheetBrowser.entries.push(
      { bank: previewBank, source: 'devoirs/2026-2027/ds.typ', documentType: 'devoir', metadata: [sourceMetadata('titre: "Devoir test"', 'devoirs/2026-2027/ds.typ')] },
      { bank: previewBank, source: 'concours/24/sujet.typ', documentType: 'concours', metadata: [sourceMetadata('titre: "Concours test"', 'concours/24/sujet.typ')] });
    sheetBrowser.filters = {};
    const roots = sheetBrowser.getChildren();
    assert.deepEqual(roots.map(root => isFolder(root) && root.title), ['concours', 'devoirs', 'feuilles']);
    const devoirParent = sheetBrowser.getParent(sheetBrowser.entries[1]);
    assert.ok(devoirParent && isFolder(devoirParent) && devoirParent.title === '2026-2027');
    const devoirRoot = sheetBrowser.getParent(devoirParent);
    assert.ok(devoirRoot && isFolder(devoirRoot) && devoirRoot.title === 'devoirs');
    sheetBrowser.filters = { type: 'concours' };
    assert.equal(sheetBrowser.visible.length, 1);
    assert.equal(sheetBrowser.search('Concours').length, 1);
    assert.equal(sheetBrowser.getChildren().length, 1);
    sheetBrowser.filters = { type: 'absent' };
    assert.deepEqual(sheetBrowser.getChildren(), [], 'Aucun dossier sans fichier correspondant aux filtres');
    const originalEntries = [...sheetBrowser.entries];
    const otherBank = { ...previewBank, root: temporary + '-autre', name: 'Autre banque' };
    sheetBrowser.entries.push({ ...originalEntries[0], bank: otherBank });
    sheetBrowser.filters = { type: 'concours' };
    const filteredRoots = sheetBrowser.getChildren();
    assert.equal(filteredRoots.length, 1, 'Aucune racine de banque vide');
    assert.ok(isFolder(filteredRoots[0]) && filteredRoots[0].title === 'concours');
    sheetBrowser.filters = {};
    sheetBrowser.entries = [];
    assert.deepEqual(sheetBrowser.getChildren(), [], 'La suppression du dernier fichier retire ses dossiers');
    sheetBrowser.entries = originalEntries;
    sheetBrowser.filters = {};
    sheetBrowser.toggle(); assert.equal(sheetBrowser.getChildren().length, 3);
    assert.ok(sheetBrowser.getChildren().every(node => !isFolder(node)));
    assert.ok(searchItem(sheetBrowser.entries[1]).detail?.includes('Devoir'));
    sheetBrowser.dispose();
    const sheet = sheetFromTemplate(await readFile(path.join(bank, 'templates/feuille.typ'), 'utf8'), 'Feuille de test', [relative]);
    await writeFile(path.join(temporary, 'feuilles/test-creation.typ'), sheet);
    const sheetEditor = new Sheets(() => [previewBank], () => [{ bank: previewBank, ex: sourceMetadata(generated, relative) }]);
    const members = await sheetEditor.members(previewBank, 'feuilles/test-creation.typ');
    assert.equal(members[0].title, 'Test création');
    assert.equal(memberItem(members[0]).label, '1. Test création');
    assert.equal(memberItem(members[0]).resourceUri?.fsPath, path.join(previewBank.root, relative));
    await sheetEditor.change(members[0]);
    const sheetDocument = await vscode.workspace.openTextDocument(vscode.Uri.file(path.join(temporary, 'feuilles/test-creation.typ')));
    assert.equal(sheetList(sheetDocument.getText(), 'feuilles/test-creation.typ').entries.length, 0);
    assert.ok(!sheetDocument.isDirty, 'Retrait enregistré automatiquement');
    assert.ok(!sheetDocument.getText().includes('/' + relative), 'Import retiré');
    await sheetEditor.add(previewBank, relative, 'feuilles/test-creation.typ');
    assert.equal(sheetList(sheetDocument.getText(), 'feuilles/test-creation.typ').entries.length, 1);
    assert.ok(!sheetDocument.isDirty, 'Ajout enregistré automatiquement');
    await assert.rejects(sheetEditor.change({ ...members[0], snapshot: 'obsolete' }), /changé/);
    sheetEditor.selected = { bank: previewBank, source: 'feuilles/selection.typ' };
    sheetEditor.current = { bank: previewBank, source: 'feuilles/autre.typ' };
    assert.equal(sheetEditor.target?.source, 'feuilles/selection.typ');
    const moved: string[] = [];
    const drag = new Drag<any>(() => sheetEditor, async (_from, to) => { moved.push(to); }, error => { throw error; });
    const transfer = new vscode.DataTransfer();
    drag.handleDrag([{ bank: previewBank, source: relative }], transfer);
    await drag.handleDrop({ bank: previewBank, source: 'exercices', folder: 'exercices' }, transfer);
    assert.deepEqual(moved, ['exercices/test-creation.typ']);
    const devoirPath = 'devoirs/2026-2027/ds-test.typ';
    const devoir = sheetFromTemplate(await readFile(path.join(bank, 'templates/devoir.typ'), 'utf8'), 'Devoir de test', []);
    await writeFile(path.join(temporary, devoirPath), devoir);
    const devoirDocument = await vscode.workspace.openTextDocument(vscode.Uri.file(path.join(temporary, devoirPath)));
    assert.equal(sheetEditor.locate(devoirDocument.uri)?.source, devoirPath);
    await sheetEditor.add(previewBank, relative, devoirPath);
    const devoirMembers = await sheetEditor.members(previewBank, devoirPath);
    assert.equal(devoirMembers[0].title, 'Test création');
    assert.ok(!devoirDocument.isDirty);
    await sheetEditor.change(devoirMembers[0]);
    assert.ok(!devoirDocument.getText().includes('/' + relative));
    // Exercise-to-devoir drops compose; blank unified-view drops keep the physical type.
    const sheetDrag = new Drag<any>(() => sheetEditor, async (_from, to) => { moved.push(to); }, error => { throw error; });
    await sheetDrag.handleDrop({ bank: previewBank, source: devoirPath }, transfer);
    assert.equal((await sheetEditor.members(previewBank, devoirPath)).length, 1);
    const devoirTransfer = new vscode.DataTransfer();
    sheetDrag.handleDrag([{ bank: previewBank, source: devoirPath }], devoirTransfer);
    await sheetDrag.handleDrop(undefined, devoirTransfer);
    assert.equal(moved.at(-1), 'ds-test.typ');
    await assert.rejects(sheetEditor.add(previewBank, relative, relative), /Choisissez un document/);
    await sheetDocument.save(); sheetEditor.dispose();
    await runner.run(previewBank, ['c', 'feuilles/test-creation.typ']);
    await runner.run(previewBank, ['c', devoirPath]);
    for (const variant of ['enonce', 'corrige']) assert.ok((await stat(path.join(temporary, `build/devoirs/2026-2027/ds-test/${variant}.pdf`))).size > 1000);
    const devoirPreview = await previews.open(previewBank, devoirPath, 'enonce');
    assert.equal(devoirPreview.panel.title, 'ds-test.pdf');
    assert.ok(devoirPreview.native);
    await devoirPreview.select('corrige');
    assert.equal(devoirPreview.panel.title, 'ds-test-cor.pdf');
    // No category prefix, no mandatory year folder, and a new type without code changes.
    const customSource = sheetFromTemplate(customTemplate, 'Colle à la racine', [relative]);
    await writeFile(path.join(temporary, 'colle-test.typ'), customSource);
    assert.equal(identify(customSource, 'colle-test.typ')?.type, 'colle');
    await runner.run(previewBank, ['c', 'colle-test.typ']);
    assert.ok((await stat(path.join(temporary, 'build/colle-test/corrige.pdf'))).size > 1000);
    const contestPath = creationPath('concours/24', 'sujet-test');
    await mkdir(path.join(temporary, 'concours/24'), { recursive: true });
    await writeFile(path.join(temporary, contestPath), contestFromTemplate(await readFile(path.join(temporary, 'templates/sujet-concours.typ'), 'utf8'), 'Sujet de test'));
    await runner.run(previewBank, ['c', contestPath]);
    for (const variant of ['enonce', 'corrige']) assert.ok((await stat(path.join(temporary, 'build/concours/24/sujet-test', variant + '.pdf'))).size > 1000);
    const fallback = new Previews({ extensionUri: extension.extensionUri } as vscode.ExtensionContext, async () => undefined, () => false);
    try {
      const pdfPreview = await fallback.open(previewBank, relative, 'enonce');
      assert.equal(pdfPreview.jumps, false); assert.equal(pdfPreview.native, false);
      let pdfReady = 0;
      const pdfListener = pdfPreview.panel.webview.onDidReceiveMessage(message => { if (message.type === 'pdfError') console.error(message.error); if (message.type === 'pdfReady') pdfReady++; });
      pdfPreview.panel.reveal(vscode.ViewColumn.Beside);
      await pdfPreview.restart();
      await until(() => pdfReady > 0, 'PDF affiché sans Tinymist');
      await pdfPreview.toggleJumps(); assert.equal(pdfPreview.jumps, false);
      const firstRender = pdfReady;
      await pdfPreview.select('corrige');
      await until(() => pdfReady > firstRender, 'Corrigé PDF affiché sans Tinymist');
      pdfListener.dispose();
    } finally { fallback.dispose(); }
    assert.equal(relocated('#import "../../lib/exercices.typ": exercice\n#image("../../ressources/a.png")', relative, relative, 'exercices/test-creation.typ'), '#import "../lib/exercices.typ": exercice\n#image("../ressources/a.png")');
    assert.ok((await directories(previewBank, 'exercices')).some(item => item.source === 'exercices/graphes'));
    assert.ok(preview.panel.webview.html.includes('id="jumps"') && preview.panel.webview.html.includes('id="corrige"'));
    await preview.toggleTheme();
    assert.equal(preview.dark, !dark, 'Thème inversé localement');
    const themed = preview.sessions.get('enonce')!;
    assert.notEqual(themed, enonce);
    const themedSocket = new WebSocket(`ws://127.0.0.1:${themed.port}`); sockets.push(themedSocket);
    const themedMessages: string[] = []; themedSocket.binaryType = 'arraybuffer';
    themedSocket.addEventListener('message', event => themedMessages.push(typeof event.data === 'string' ? event.data : Buffer.from(event.data as ArrayBuffer).toString()));
    await until(() => themedSocket.readyState === WebSocket.OPEN, 'Connexion au rendu avec thème inversé'); themedSocket.send('current');
    await until(() => themedMessages.some(data => data.includes(`"rest":"${dark ? 'never' : 'always'}"`)), 'Le moteur utilise le thème inversé');
    await moveSource({ bank: previewBank, source: relative }, 'test-creation.typ');
    assert.ok(sheetDocument.getText().includes('/test-creation.typ'), 'Références actualisées après déplacement à la racine');
    assert.ok((await stat(path.join(temporary, 'test-creation.typ'))).size > 0);
    await assert.rejects(stat(file));
    listener.dispose();
    if (process.env.PREVIEW_REVIEW) { console.log('Aperçu temporaire', enonce.url); await new Promise(resolve => setTimeout(resolve, 55_000)); }
    preview.panel.dispose();
    devoirPreview.panel.dispose();
    assert.equal(previews.entries.size, 0);
  } finally {
    for (const socket of sockets) socket.close();
    previews.dispose(); runner.dispose();
    await rm(temporary, { recursive: true, force: true });
  }
  console.log('Intégration complète réussie. Aucun PDF de la banque inspecté.');
}
